# Generated by Django 5.2.8 on 2026-01-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_type_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('gaming', 'Gaming'), ('food', 'Food'), ('electronics', 'Electronics'), ('sports', 'Sports')], default='electronics', max_length=20, null=True),
        ),
    ]
